smarts:
  seed: 42
  visdom: False
  rgb_meters: 64 # Height and width (meters) of RGB image in SMARTS observation
  rgb_pixels: 64 # Height and width (pixels) of RGB image in SMARTS observation  
  max_episode_steps: 300 # 30 seconds. Maximum steps per episode.
  action_space_type: "Continuous"
  agent_ids: 
    - Tiger1
  scenarios: 
    - loop
