# Task 3 will be focusing on training on "n" number of lanes and testing on "n+1" number of lanes. For now, all
# training and testing sets are going to have the same number of traffic densities

levels:
  grade1:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.05],[70kmh,mid-density,0.05],[100kmh,mid-density,0.05], #15%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
    test:
      total: 150
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,no-traffic,0.15],[70kmh,no-traffic,0.15],[100kmh,no-traffic,0.15], #45%
                   [50kmh,low-density,0.085],[70kmh,low-density,0.085],[100kmh,low-density,0.08], #25%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.035],[70kmh,high-density,0.035],[100kmh,high-density,0.03]] #10%
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  grade2:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,no-traffic,0.05],[70kmh,no-traffic,0.05],[100kmh,no-traffic,0.05], #15%
                   [50kmh,low-density,0.20],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #60%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
    test:
      total: 150
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,no-traffic,0.07],[70kmh,no-traffic,0.07],[100kmh,no-traffic,0.06], #20%
                   [50kmh,low-density,0.15],[70kmh,low-density,0.15],[100kmh,low-density,0.15], #45%,
                   [50kmh,mid-density,0.085],[70kmh,mid-density,0.085],[100kmh,mid-density,0.08], #25%
                   [50kmh,high-density,0.035],[70kmh,high-density,0.035],[100kmh,high-density,0.03]] #10%
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  grade3:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.20],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #60%
                   [50kmh,high-density,0.07],[70kmh,high-density,0.07],[100kmh,high-density,0.06]] #20%
    test:
      total: 150
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,no-traffic,0.035],[70kmh,no-traffic,0.035],[100kmh,no-traffic,0.03], #10%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.15],[70kmh,mid-density,0.15],[100kmh,mid-density,0.15], #45%
                   [50kmh,high-density,0.085],[70kmh,high-density,0.085],[100kmh,high-density,0.08]] #25%
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  grade4:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,high-density,0.07],[70kmh,high-density,0.07],[100kmh,high-density,0.06], #20%
                   [50kmh,mid-density,0.20],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20]] #60%
    test:
      total: 150
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,no-traffic,0.035],[70kmh,no-traffic,0.035],[100kmh,no-traffic,0.03], #10%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,high-density,0.085],[70kmh,high-density,0.085],[100kmh,high-density,0.05], #25%
                   [50kmh,mid-density,0.15],[70kmh,mid-density,0.15],[100kmh,mid-density,0.15]] #45%