smarts:
  # Environment
  sumo_gui: False # If True, enables sumo-gui display.
  img_meters: 50 # Observation image area size in meters.
  img_pixels: 112 # Observation image size in pixels.
  num_stack: 3 # Number of frames to stack as input to policy network.
  action_space: "Continuous"
  action_wrapper: "Discrete"
  scenarios: 
    - "1_to_2lane_left_turn_c"
    - "1_to_2lane_left_turn_t"
    - "3lane_merge_single_agent"
    - "3lane_cruise_single_agent"
    - "3lane_overtake"

  # Training
  epochs: 5e3 # Number of training loops.

  # Trianing per scenario
  train_steps: 1e5
  checkpoint_freq: 5e4 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 100 # Number of evaluation epsiodes.
  eval_freq: 5e4 # Evaluate the trained model every eval_freq steps and save the best model.

  # Policy
  alg: PPO  # Stable Baselines3 algorithm.
  alg_kwargs: combined_extractor
