smarts:
  # Environment
  sumo_gui: True # If True, enables sumo-gui display.
  img_meters: 50 # Observation image area size in meters.
  img_pixels: 112 # Observation image size in pixels.
  num_stack: 3 # Number of frames to stack as input to policy network.
  scenarios: 
    - "1_to_2lane_left_turn_c"
    - "1_to_2lane_left_turn_t"
    - "3lane_merge_single_agent"
    - "3lane_cruise_single_agent"
    - "3lane_overtake"

  # Training
  epochs: 5_000 # Number of training loops.

  # Training per scenario
  train_steps: 5_000
  checkpoint_freq: 2_500 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 10 # Number of evaluation epsiodes.
  eval_freq: 2_500 # Evaluate the trained model every eval_freq steps and save the best model.

  # Policy
  alg: PPO  # Stable Baselines3 algorithm.
