levels:
  lo-hi:
    train:
      total: 800
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
        3lane_t:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.20],[100kmh,high-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%
        3lane_t:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.20],[100kmh,high-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%
  hi-low:
    train:
      total: 800
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.20],[100kmh,high-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%
        3lane_t:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.20],[100kmh,high-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
        3lane_t:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
