name: SMARTS CI Auto Commit Linux

on:
  push:
    branches:
      - master

env:
  venv_dir: .venv

jobs:
  auto-commit-linux:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.6.1-minimal
    steps:
      - name: Install packages
        run: |
          add-apt-repository -y ppa:git-core/ppa
          apt-get update
          apt-get install -y git curl ca-certificates
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
      - name: Add safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install SMARTS
        run: |
          python3.8 -m venv ${{env.venv_dir}}
          . ${{env.venv_dir}}/bin/activate
          pip install --upgrade pip
          pip install wheel==0.38.4
          pip install .[camera_obs,rllib,test,torch,train]
      - name: Update requirements
        run: |
          . ${{env.venv_dir}}/bin/activate
          pip freeze | grep -v 'smarts' | grep -v 'pkg-resources==0.0.0' > requirements.txt
      - name: Commit requirement changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "requirements.txt"
          branch: master
          default_author: user_info
          message: "GitHub Actions: Update requirements.txt"
      - name: isort, Black, and prettier
        run: |
          . ${{env.venv_dir}}/bin/activate
          pip install .[dev]
          isort -m VERTICAL_HANGING_INDENT --skip-gitignore --ac --tc --profile black ./cli ./envision ./examples/ ./utils/ ./scenarios/ ./smarts ./zoo
          black .
          npx prettier --write ./envision/web/src
      - name: Commit format changes
        uses: EndBug/add-and-commit@v7
        with:
          add: '["*.py", "*.html", "*.js"]'
          branch: master
          default_author: user_info
          message: "GitHub Actions: Format"
