name: SMARTS CI Python Version Tests

# on:
#   push:
#     branches:
#       - master
on: [push, pull_request]


env:
  venv_dir: .venv

jobs:
  install_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10-dev', '3.11-dev']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update requirements
        run: |
          cd $GITHUB_WORKSPACE
          python${{ matrix.python-version }} -m venv ${{env.venv_dir}}
          . ${{env.venv_dir}}/bin/activate
          pip install --upgrade pip
          pip install wheel==0.38.4
          pip install .[camera_obs,rllib,test,torch,train]