name: SMARTS CI Long Determinism

on:
  schedule:
    - cron: '0 23 * * 6'
      # Time is in UTC
      # Runs at 11.00pm, UTC  , every Saturday
      # Runs at  7.00pm, UTC-4, every Saturday
  workflow_dispatch:

env:
  venv_dir: .venv

jobs:
  test_learning:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Setup package
        run: |
          cd $GITHUB_WORKSPACE
          python3.7 -m venv ${{env.venv_dir}}
          . ${{env.venv_dir}}/bin/activate
          pip install --upgrade pip
          pip install -e .[train,test,camera-obs]
      - name: Verify long determinism
        run: |
          cd $GITHUB_WORKSPACE
          . ${{env.venv_dir}}/bin/activate
          make test-long-determinism