name: SMARTS CI Header

on: [push, pull_request]

env:
  venv_dir: .venv

jobs:
  test-header:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check header
        run: |
          cd $GITHUB_WORKSPACE
          make header-test