name: SMARTS CI Memory

on:
  schedule:
    - cron: '0 23 * * 4'
      # Time is in UTC
      # Runs at 11.00pm, UTC  , every Thursday
      # Runs at  7.00pm, UTC-4, every Thursday
  workflow_dispatch:

env:
  venv_dir: .venv

jobs:
  test_memory:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Setup package
        run: |
          cd $GITHUB_WORKSPACE
          python3.7 -m venv ${{env.venv_dir}}
          . ${{env.venv_dir}}/bin/activate
          pip install --upgrade pip
          pip install wheel
          pip install pympler
          pip install -r requirements.txt
          pip install -e .[train,test,camera-obs]
      - name: Test memory growth
        run: |
          cd $GITHUB_WORKSPACE
          . ${{env.venv_dir}}/bin/activate
          make test-memory-growth